### ISSUE TITLE
Unmute does not occur when ads are done

### ISSUE THREAD

**Issue by techvice** [GUiHKX/spotishush#2]
After an ad or two has concluded, plugin does not seem to unmute the tab. I am ending up having to manually unmute the tab. 

I know at least one user has reported the same issue via [Support tab from the Chrome Web Store](https://chrome.google.com/webstore/detail/spotishush/dfbbfmkkafpoohlcmkndjnpohhgelgnf/support).

**Comment by GUiHKX** [comment]
This should be fixed in v2018.6.19. Let me know if it works for you.

Thanks for reporting

**Comment by techvice** [comment]
@GUiHKX - Works for me. Thanks!
