### ISSUE TITLE
Tidal not muting ads after June 21, 2022 update

### ISSUE THREAD

**Issue by saint-etienne** [guihkx/spotishush#25]
Hi. After updating the web player. The ads are playing again.

**Comment by guihkx** [comment]
Just tested it here, still mutes for me 🤔 

![Screenshot from 2022-06-29 14-09-12](https://user-images.githubusercontent.com/626206/176496082-09be86ca-f51d-4b58-8582-adb4f1772766.png)

Can you open the developer console of your browser and take a screenshot of the Console tab (like I did above)?

**Comment by saint-etienne** [comment]
Nevermind. Figured out it's the "Volume Master" extension, volume controlling slider, that breaks the mute in the tab when enabled.

**Comment by guihkx** [comment]
Glad you figured it out!
