### ISSUE TITLE
Request for IDAGIO support

### ISSUE THREAD

**Issue by vsl7** [guihkx/spotishush#27]
Thank you for the extension. Please add support also for [IDAGIO](https://app.idagio.com), because it seems like audio ads there cannot be blocked in other ways.

**Comment by guihkx** [comment]
I just published a new release with IDAGIO support. I didn't know this site, very cool.

As of now, only Firefox has the latest version published in their Webstore, but it shouldn't take too long for the other browsers to catch up.

I did some testing for an hour or so and all ads were successfully muted.

Nevertheless, please do your own tests as well, and create a new issue if you encounter any problems.

Thanks.

**Comment by vsl7** [comment]
It works, thank you.
