### ISSUE TITLE
Doesn't unmute (w/ ublock) - Ver 2022.10.19

### ISSUE THREAD

**Issue by saint-etienne** [guihkx/spotishush#28]
Previous version has no issues with "ublock".

Must be something with the timing when an ad plays for a second, is blocked & gets muted at the same time. When songs resume, they stay muted. 
No issues when ublock is disabled.

**Comment by guihkx** [comment]
On what streaming service?

FWIW, SpotiShush is not really intended to use alongside an ad blocker. In fact, I created SpotiShush to avoid using an ad blocker on music streaming services. Plus, as far as I know, uBlock Origin should block all kinds of ads, audio included. 🤔

**Comment by saint-etienne** [comment]
Web player. Some people use spotishush w/ ublock as a backup 😁
Sometimes, spotify updates their adflow that breaks ublock for a while then spotishush will take care of things.

**Comment by guihkx** [comment]
Ah, gotcha.

Well, I'm afraid there isn't much I can do here, because I have no clue what uBlock is doing to trip SpotiShush into not being able to unmute the tab afterward.

I'll try to reproduce/investigate this for a couple more days, but in the end I think the best I can do is to update the README and recommend people to avoid using an ad blocker and SpotiShush simultaneously, at least on websites supported by SpotiShush. :/

**Comment by saint-etienne** [comment]
Thanks. Awesome app, as always

**Comment by guihkx** [comment]
No problem :)

If you can, please try to reproduce this issue again, but this time with the developer console open in the 'Console' tab, e.g.:

![image](https://user-images.githubusercontent.com/626206/166677308-fc3fa2d4-3581-4452-a5b5-9a5b0f630271.png)

Then take a screenshot and post it here, maybe some error will popup...

**Comment by guihkx** [comment]
I tested this three different times on Chrome 107 / uBlock Origin 1.44.4, and everything still works:

https://user-images.githubusercontent.com/626206/197894700-5f1ea8b0-e3fb-414c-8821-ec518d9324f8.mp4

https://user-images.githubusercontent.com/626206/197894935-9ae8c4a9-6fe3-4524-bbc0-e56bea1426bb.mp4

https://user-images.githubusercontent.com/626206/197895057-2d4cfcc2-8715-4f64-a5cd-2fc0ef2a7adb.mp4

This is how uBlock Origin blocks Spotify audio ads:

1. They detect the audio ad before it plays.
2. They replace the audio file by a custom MP3 that "plays silence" for 0,5s.

The current uBlock rule for Spotify can be found here: https://github.com/uBlockOrigin/uAssets/blob/5c62bfa1de656fe01b2d6c1ba38c7566e4c0c1a4/filters/filters-2020.txt#L1907-L1912

So, if you watch the video, even after uBlock Origin replaces the original audio ad by a dummy mp3, SpotiShush was still able to detect it and muted the tab accordingly. And most importantly, it was successfully able to unmute the tab afterward.

I think your issue might have been just a fluke, which I've had many times on Spotify, unfortunately. But just make sure to update your uBlock filters when this stuff happens again.

But ultimately, I'd advise against combining uBlock Origin and SpotiShush on sites that SpotiShush supports.
