### ISSUE TITLE
Doesn't work on Deezer

### ISSUE THREAD

**Issue by notdev007** [guihkx/spotishush#30]
Hi, I installed spotishush but it doesn't mute tab on Deezer.
Chrome Build: Version 108.0.5359.124 (Official Build) (64-bit)

In console when ad starts playing:
[SpotiShush v2022.10.19] [Deezer] Ad error, unmuting tab...
spotishush.js:67 [SpotiShush v2022.10.19] [Deezer] Warning: This tab is already unmuted, not doing anything. Details: {muted: false}
Any ideas what can be wrong?

**Comment by guihkx** [comment]
Hi, thanks for reporting.

Can confirm, it stopped working on Deezer.

I'll investigate!
