### ISSUE TITLE
Recent problems on Deezer

### ISSUE THREAD

**Issue by johansenja** [guihkx/spotishush#32]
Hi there, love the extension! 🙏🏻 

I had a long-open tab in Deezer (chrome) which was working great, but then I closed and reopened it (earlier today), and the extension seems to have stopped working.

Anyone else have similar problems?

**Comment by guihkx** [comment]
Hey, thanks for the report.

I've only had time to look at this problem today, but unfortunately Deezer has been really crappy and simply 'crashes' every time an ad is about to play (actual songs play just fine):

![image](https://github.com/guihkx/spotishush/assets/626206/aafcbd85-89ff-4f8e-a28a-ef836c374469)


I get the same behavior regardless of web browser, which might indicate a problem on their end.

In any case, I'll continue to investigate this.

Thanks

**Comment by guihkx** [comment]
Should be fixed now! Please open a new issue if you find problems.

I'm in the process of publishing a new version, which should be available on all web stores today.

**Comment by johansenja** [comment]
Legend, thank you 🙏🏻
