### ISSUE TITLE
For me is not working in Firefox IDAGIO

### ISSUE THREAD

**Issue by 9acca9** [guihkx/spotishush#35]
hi.
It seems that when an ad begin is muted but the sound never come back.
I can do something?
Share some log? how get the log? thanks!

**Comment by guihkx** [comment]
Hi, thanks for reporting.

Based on an initial impression, it seems like IDAGIO itself "crashes" when an ad is about to play:

![image](https://github.com/guihkx/spotishush/assets/626206/dbdde61b-1435-4ceb-91b2-4368c23d6f9a)

Also, I was able to reproduce this this even with SpotiShush disabled, which might indicate this is IDAGIO's own fault...

In any case, I'll keep this open so I can continue to investigate this in the next days.

>how get the log?

You can open the developer console (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) and screenshot the "Console" tab. That should be enough, I think.

**Comment by guihkx** [comment]
Okay, it seems like IDAGIO has fixed itself. 

At least here, SpotiShush is able to mute/unmute the tab correctly. Can you please re-check? Thank you.
