### ISSUE TITLE
Spotishush not working on Firefox.

### ISSUE THREAD

**Issue by EkanshdeepGupta** [guihkx/spotishush#5]
I know how frustrating it can be to receive such a vague issue, so let me clarify at the outset that I want to provide any info that you might need to help debug this. It's that I don't know where to collect any relevant information or extension logs etc. Here's the information I do have:

Browser: Firefox 70.0.1 (64-Bit)
OS: Fedora KDE 30
Spotishush version: 2018.6.19

I installed the extension and restarted the browser (for good measure). However when I play some music on open.spotify.com and an ad shows up, it does not mute the tab even though the tab title contains "Advertisement" (which is how I'm assuming the extension checks for ads). Some things that might be tripping it up:
* I use multiple Firefox windows, and have a dedicated window with just the Spotify tab.
* I use multiple other extensions, like uBlock, Pause/Play and Plasma Integration.

It seems implausible that one of these things is causing the issue but I am just putting this out there for good measure.

Thanks for your time.

**Comment by guihkx** [comment]
I was experiencing the same problem earlier today, but I had uBlock Origin enabled (it's pointless to have both Spotishush and uBlock enabled for Spotify). Anyway, I'll have to investigate this further. Thanks for reporting.

**Comment by guihkx** [comment]
So, I did some quick testing in a new Firefox profile with default options and no extensions, except SpotiShush. Both ad detection (which doesn't work like you think it does) and tab muting still work just fine:

* Here's the developer console log of when the ad is detected **(notice that the tab is muted)**:
![Screenshot_20191202_204232](https://user-images.githubusercontent.com/626206/70004525-5454ed00-1545-11ea-89f2-b9aaeaf7acba.png)

* Another ad played in sequence, the tab still remained muted:
![Screenshot_20191202_204305](https://user-images.githubusercontent.com/626206/70004564-81a19b00-1545-11ea-9533-b7a90a0c13f7.png)

* And finally, the tab was unmuted:
![Screenshot_20191202_204337](https://user-images.githubusercontent.com/626206/70004576-8c5c3000-1545-11ea-89e1-1963f752632d.png)


However, as I mentioned earlier, I was too having some issues. But in my case, I was on Chromium and songs would playing randomly. There was this one time when SpotiShush muted the tab when no ad was playing, though, so I had to close the tab and open it again. That's a different bug I need to work on...

Anyway, I'll keep this issue open for some time. If you want to help me debug this, you could try leaving the developer console open (<kbd>Ctrl</kbd>+<kbd>Shift</kbd>+<kbd>I</kbd>) on the `Console` tab, then when an ad starts playing, you take a screenshot and post it here.

**Comment by EkanshdeepGupta** [comment]
Hi, I think the issue is caused by the Pause/Play extension which I had enabled on Firefox, the purpose of which is supposed to allow audio/video pause and play with the tab-mute button. I believe that must be interfering with the functionality of Spotishush, but once I disabled that, the extension is working as intended. Thanks.

**Comment by guihkx** [comment]
Glad to hear that!

Feel free to re-open this issue if you still experience problems.
