### ISSUE TITLE
It doesn't work anymore (?)

### ISSUE THREAD

**Issue by Oneiros90** [guihkx/spotishush#9]
Hi, I love your extension.
However it seems that it stopped working today, maybe something changed in Spotify Web Player?
I'm using Firefox.

Thanks!

**Comment by guihkx** [comment]
Hey, thanks for reporting! 

I'm sorry to hear that, but unfortunately I won't be able to take a proper look at this because I don't have any computer or laptop available right now... :(

I'll do my best to fix it asap at the beginning of next week, though.

Thanks

**Comment by davidearlyoung** [comment]
Hello,

I'm having the same issue as Oneiros90. 
I'm seeing the issues with Google Chrome ver. 89.0.4389.90 (Official Build) (64-bit) on Windows 10 Home.
Looks like chrome had some major changes with their recent updates. Could be that it's a simple change on their part that's effecting how your extension works.  I'm hoping that it's really simple to find and adjust for for when you have the ability to. Really appreciate this extension.

**Comment by lastminutegoals** [comment]
If that's of any help, can also confirm it also stopped working for me properly since a day or two ago.

Firefox 86.0 (64-bit) on Ubuntu 20.04

**Comment by MohsenneChaverdie** [comment]
Same problem with Google Chrome ver. 89.0.4389.90.

**Comment by miraic** [comment]
Same problem here with Firefox 86.0.1 on MacOS.

**Comment by Miranda-J** [comment]
I'm also having the same issue (both on a mac and windows computer. To try to help with troubleshooting when you get time to look at this, I'm attaching a screen shot of the 'web console' messages when the add on tries to activate: 
![Bild1](https://user-images.githubusercontent.com/5290103/111961508-72a37b00-8af1-11eb-923d-5025ca6d16fe.png)

Hope this gets worked out soon, I really like this add on!

**Comment by guihkx** [comment]
Hi folks!

I've tested this new change for a couple of hours on Firefox/Chrome and it seems to be working like it used to.

So I'll be releasing version 2021.3.23 very soon in both Firefox Addons and Chrome Webstore very soon, so don't forget to update before testing it out. :)

And as always, if you guys find any issues, feel free to post them here or create a new issue.

Thanks
